[workspace]

members = [
    "./hello_world",
    "./primitives",
    "./custom_types",
    "./variable_bindings",
    "./types_",
    "./conversion",
    "./flow_of_control",
    "./functions",
    "./modules_",
    "./crates",
    "./attributes",
    "./generics"
]